#!/usr/bin/env python

def EmailTestReport():
    import mailer
    message = mailer.Message()
    message.From = 'jbanerje@cisco.com'
    message.To = 'jbanerje@noironetworks.com'
    message.Body = 'This Email contains GBP-Opflex Test Report\n This is an AutoGenerated Email\n DO NOT REPLY'
    message.attach("/root/noiro_test_report.html")
    mailer = mailer.Mailer("outbound.cisco.com")
    mailer.send(message)

def main():
    EmailTestReport()

if __name__ == '__main__':
    main()
